In [12]:
import pandas as pd
import os

In [3]:
df = pd.read_excel("data/original/restaurant_reviews-v2-1.xlsx")

In [4]:
df.head()

,Restaurant,Review,Real=1/Fake=0,positive=1/negative=0,AWL,ASL,NOW,NVB,NAJ,NPV,NST,CDV,NTP,TPR
0,Tikka Shack,Great food and great atmosphere! The chicken t...,0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Tikka Shack,I had heard good things about Tikka Shak so I ...,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Tikka Shack,I was driving by tikka shack one day and decid...,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Tikka Shack,Tikka Shack had the most modern and up-to-date...,0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,India Palace\nIndian\nRestaurant,Today is the third time I've come to India Pal...,0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 260 entries, 0 to 259
Data columns (total 14 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Restaurant             260 non-null    object
 1   Review                 260 non-null    object
 2   Real=1/Fake=0          260 non-null    int64
 3   positive=1/negative=0  260 non-null    int64
 4   AWL                    0 non-null      float64
 5   ASL                    0 non-null      float64
 6   NOW                    0 non-null      float64
 7   NVB                    0 non-null      float64
 8   NAJ                    0 non-null      float64
 9   NPV                    0 non-null      float64
 10  NST                    0 non-null      float64
 11  CDV                    0 non-null      float64
 12  NTP                    0 non-null      float64
 13  TPR                    0 non-null      float64
dtypes: float64(10), int64(2), object(2)
memory usage: 28.6+ KB

In [8]:
df = df.dropna(axis=1)
df = df.drop(['Real=1/Fake=0', 'Restaurant'], axis=1)

In [9]:
df.head()

                                              Review  positive=1/negative=0
0  Great food and great atmosphere! The chicken t...                      1
1  I had heard good things about Tikka Shak so I ...                      0
2  I was driving by tikka shack one day and decid...                      0
3  Tikka Shack had the most modern and up-to-date...                      1
4  Today is the third time I've come to India Pal...                      1

In [10]:
"""
  Helper function to save datasets to csv files.
"""
def save_csv(df, output_dir, filename):

  if not os.path.exists(output_dir):
      os.makedirs(output_dir)

  full_path = output_dir + filename

  df.to_csv(full_path, index=False)
  print(f"{filename} saved.")

In [11]:
save_csv(df, 'data/preprocessed/', 'reviews_sentiment_analysis.csv')

reviews_sentiment_analysis.csv saved.